name: Deploy to Server

on:
  push:
    branches:
      - main  # Указывай свою основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest  # Выбираем Ubuntu как окружение для CI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Шаг для клонирования репозитория

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519  # Загружаем SSH ключ из секретов
        chmod 600 ~/.ssh/id_ed25519  # Устанавливаем правильные права на ключ
        ssh-keyscan -H 16.171.182.173 >> ~/.ssh/known_hosts  # Добавляем публичный ключ сервера в known_hosts
        chmod 600 ~/.ssh/known_hosts  # Устанавливаем права для файла known_hosts

    - name: Copy files to server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ubuntu@16.171.182.173 "mkdir -p /home/ubuntu/Messgaes_bot"  # Создаем папку на сервере
        scp -i ~/.ssh/id_ed25519 -r * ubuntu@16.171.182.173:/home/ubuntu/Messgaes_bot  # Копируем файлы на сервер

    - name: Restart bot
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ubuntu@16.171.182.173 "cd /home/ubuntu/Messgaes_bot && git pull && sudo systemctl restart tg_bot"  # Перезапускаем сервис
