name: Deploy to Server

on:
  push:
    branches:
      - main  # Указывай свою основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest  # Выбираем Ubuntu как окружение для CI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Шаг для клонирования репозитория

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}  # Используем приватный ключ из секретов GitHub

    - name: Set up known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 16.171.182.173 >> ~/.ssh/known_hosts  # Добавляем публичный ключ сервера
        chmod 600 ~/.ssh/known_hosts  # Устанавливаем правильные разрешения на файл known_hosts

    - name: Copy files to server
      run: |
        scp -r * ubuntu@16.171.182.173:/home/ubuntu/Messgaes_bot  # Копируем файлы на сервер

    - name: Restart bot
      run: |
        ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 ubuntu@16.171.182.173 "cd /home/ubuntu/Messgaes_bot && git pull && sudo systemctl restart tg_bot"  # Перезапускаем сервис
