name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Configure SSH access
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 16.171.182.173 >> ~/.ssh/known_hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Force deploy and restart
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@16.171.182.173 << 'EOF'
        cd /home/ubuntu/Messgaes_bot
        git fetch --force origin main
        git reset --hard origin/main
        git clean -fd
        sudo systemctl stop tg_bot
        sudo systemctl start tg_bot
        sudo systemctl status tg_bot
        EOF
